// All copy is bilingual: { en, ar }. Images live in /public/img and /public/certs.
import { feminismEssay, jordanEssay } from "./data/writings-content";
import type { TimelineItem, Project, Credential, Writing, LightboxItem } from "./types";

export const NAV: string[] = ["hero", "manifesto", "about", "skills", "work", "experience", "gallery", "credentials", "writing", "contact"];

export const timeline: TimelineItem[] = [
  { date: { en: "Oct 2021", ar: "أكتوبر ٢٠٢١" }, img: "img/me-heforshe-workshop.jpg",
    h: { en: "HeForShe (UN Women) — Content Creator", ar: "HeForShe (هيئة الأمم للمرأة) — صانعة محتوى" },
    p: { en: "Joined the official Arabic HeForShe team and completed the UN “I Know Gender” course (16 modules). Began publishing research-rich articles on gender equality and human rights.", ar: "انضممتُ إلى فريق HeForShe العربي الرسمي وأكملتُ دورة الأمم المتحدة «أعرف النوع الاجتماعي» (١٦ وحدة)، وبدأتُ نشر مقالات بحثية عن المساواة وحقوق الإنسان." } },
  { date: { en: "Dec 2021", ar: "ديسمبر ٢٠٢١" }, img: "img/at-an-acm-club-event-as-a-first-year-represent.jpg",
    h: { en: "ACM — First-Year Representative", ar: "ACM — ممثلة السنة الأولى" },
    p: { en: "Stepped up in my first year on the Association for Computing Machinery student chapter — organising, teaching assistance, and carrying student voices to leadership.", ar: "تقدّمتُ في سنتي الأولى ضمن نادي ACM الطلابي — تنظيمًا، ومساعدةً في التدريس، ونقلًا لأصوات الطلبة إلى القيادة." } },
  { date: { en: "2022", ar: "٢٠٢٢" }, img: "img/with-the-canadian-ambassador-in-her-house-for.jpg",
    h: { en: "A year of stepping forward", ar: "عامٌ من المبادرة" },
    p: { en: "GDVC Event Manager · ACM Secretary · HTU Math Marathon Finalist (top 20 of 70+) · WikiGap contributor, honoured at the Canadian Ambassador’s residence · WeRise trophy · Ana Usharek · Women in Tech · PG Connects Jordan · AWS certified.", ar: "مديرة فعاليات GDVC · أمينة سر ACM · متأهلة في ماراثون الرياضيات (ضمن أفضل ٢٠ من ٧٠+) · مساهِمة في WikiGap وتكريم في منزل السفيرة الكندية · جائزة WeRise · أنا أشارك · المرأة في التقنية · PG Connects · شهادة AWS." } },
  { date: { en: "2023", ar: "٢٠٢٣" }, img: "img/at-a-trip-for-all-club-members-from-htu-as-a-r.jpg",
    h: { en: "Going deep on data science", ar: "التعمّق في علم البيانات" },
    p: { en: "Mentee in Women in Technology II · earned the DataCamp Associate Data Scientist certification and the Google Data Analytics Professional Certificate · recognised for university club leadership.", ar: "متدرّبة في برنامج «المرأة في التكنولوجيا II» · حصلتُ على شهادة DataCamp Associate Data Scientist وشهادة Google Data Analytics المهنية · وتكريم على قيادة الأندية." } },
  { date: { en: "Jan 2024", ar: "يناير ٢٠٢٤" }, img: "img/second-place-tahalouf-al-emarate.jpg", accent: true, tag: { en: "Award", ar: "جائزة" },
    h: { en: "2nd Place — Tahalouf Al Emarat AI Hackathon", ar: "المركز الثاني — هاكاثون تحالف الإمارات للذكاء الاصطناعي" },
    p: { en: "Took second place in a competitive regional AI hackathon — my first national-level podium, and the start of a back-to-back run.", ar: "حصلتُ على المركز الثاني في هاكاثون إقليمي تنافسي — أول منصّة تتويج وطنية لي، وبداية سلسلة متتالية." } },
  { date: { en: "2024", ar: "٢٠٢٤" }, img: "img/me-and-dr-ismael-al-hintri-htu-president-at-th.jpg",
    h: { en: "President & PwC Digital Hero", ar: "رئيسة ACM و«بطلة رقمية» في PwC" },
    p: { en: "Became President of the ACM student chapter · selected for the PwC Middle East Digital Heroes programme · HTU scholarship awardee · honoured at the HTU Excellence Ceremony by President Dr. Ismael Al Hintri.", ar: "أصبحتُ رئيسة نادي ACM · واختيرتُ لبرنامج PwC «الأبطال الرقميون» · وحاصلة على منحة الجامعة · وتكريم في حفل التميّز من رئيس الجامعة د. إسماعيل الهنتي." } },
  { date: { en: "Oct 2024", ar: "أكتوبر ٢٠٢٤" }, img: "img/hakeem-solo-win-photo-with-ceo-of-ehs-and-marw.jpg", accent: true, tag: { en: "National win", ar: "فوز وطني" },
    h: { en: "Winner — Hakeem Healthcare & AI Competition", ar: "الفوز — مسابقة حكيم للصحة والذكاء الاصطناعي" },
    p: { en: "Won the national Hakeem competition for a healthcare-focused technical solution — my second national recognition in a row.", ar: "فزتُ بمسابقة حكيم الوطنية عن حلٍّ تقني في مجال الصحة — ثاني تكريم وطني لي على التوالي." } },
  { date: { en: "2025", ar: "٢٠٢٥" }, img: "img/graduated.jpg",
    h: { en: "Graduation — and what’s next", ar: "التخرّج — وما بعده" },
    p: { en: "Presented at the PwC apprenticeship (Feb) · joined the Ahli Fintech Hackathon (Apr) · graduated with a 3.66 GPA and collected a second consecutive national-competition recognition (May). Now a 9XAI Fellow, building applied AI.", ar: "قدّمتُ عرض تدريب PwC (فبراير) · وشاركتُ في هاكاثون الأهلي فينتك (أبريل) · وتخرّجتُ بمعدل 3.66 مع تكريم وطني ثانٍ على التوالي (مايو). والآن زميلة في 9XAI أبني ذكاءً اصطناعيًا تطبيقيًا." } },
  { date: { en: "May 2026", ar: "مايو ٢٠٢٦" }, img: "img/me-with-first-place-winning-check.jpg", accent: true, tag: { en: "1st place · 3rd national win", ar: "المركز الأول · ثالث فوز وطني" },
    h: { en: "Winner — Reproductive Healthcare Solutions", ar: "الفوز — حلول الصحة الإنجابية" },
    p: { en: "Took First Place at the Najahna entrepreneurial-health competition for a reproductive-healthcare solution — my third national win in three years, and the clearest proof yet that technology for women’s health is the work I’m here to do.", ar: "حصلتُ على المركز الأول في مسابقة «نجاحنا» لريادة الصحة عن حلٍّ للصحة الإنجابية — ثالث فوز وطني خلال ثلاث سنوات، وأوضح دليل على أن التقنية لأجل صحة المرأة هي رسالتي." } },
];

export const featured: { img: string } = { img: "img/hakeem-me-presenting.jpg" };

export const projects: Project[] = [
  { win: true, year: "2026", cat: { en: "1st Place 🏆", ar: "المركز الأول 🏆" }, h: { en: "Reproductive Healthcare Solution", ar: "حلّ للصحة الإنجابية" }, p: { en: "First-place winner at the Najahna entrepreneurial-health competition — a reproductive-healthcare solution judged best in the country.", ar: "الفائز الأول في مسابقة «نجاحنا» — حلّ للصحة الإنجابية اختير الأفضل على مستوى الوطن." }, s: "healthcare · innovation · pitching" },
  { year: "2024", cat: { en: "3rd Place 🥉", ar: "المركز الثالث 🥉" }, h: { en: "The Nur Project — Hakeem Competition", ar: "مشروع نور — مسابقة حكيم" }, p: { en: "3rd place (solo) at the 9th Hakeem Academy Annual Competition by Electronic Health Solutions (EHS) — an independently built machine-learning concept predicting postpartum depression to strengthen maternal support and data research.", ar: "المركز الثالث (فردي) في مسابقة أكاديمية حكيم التاسعة من Electronic Health Solutions — مفهوم تعلّم آلة بُني منفردًا للتنبؤ باكتئاب ما بعد الولادة لتعزيز دعم الأمهات والبحث." }, s: "machine learning · health prediction · python" },
  { year: "2024", cat: { en: "2nd Place 🥈", ar: "المركز الثاني 🥈" }, h: { en: "Generative AI Hackathon", ar: "هاكاثون الذكاء الاصطناعي التوليدي" }, p: { en: "2nd place in a high-intensity generative-AI hackathon hosted by Tahaluf Al Emarat Technical Solutions at the InterContinental Amman.", ar: "المركز الثاني في هاكاثون مكثّف للذكاء الاصطناعي التوليدي من تحالف الإمارات للحلول التقنية في فندق إنتركونتيننتال عمّان." }, s: "generative ai · llms · team" },
  { year: "2024", cat: { en: "2nd Place 🥈", ar: "المركز الثاني 🥈" }, h: { en: "HTU AI Hackathon — Traffic Solutions", ar: "هاكاثون HTU للذكاء الاصطناعي — حلول المرور" }, p: { en: "2nd place in an AI hackathon hosted by HTU & KBW, building functional AI-driven traffic solutions under time pressure.", ar: "المركز الثاني في هاكاثون للذكاء الاصطناعي من HTU وKBW، ببناء حلول مرور عملية مدفوعة بالذكاء الاصطناعي تحت ضغط الوقت." }, s: "ai · transportation · teamwork" },
  { year: "2024", cat: { en: "Applied AI", ar: "ذكاء تطبيقي" }, h: { en: "Postnatal Depression Prediction", ar: "التنبؤ باكتئاب ما بعد الولادة" }, p: { en: "An AI & Intelligent Systems project comparing an artificial neural network and a decision tree to classify postnatal depression risk from health survey data.", ar: "مشروع في الذكاء الاصطناعي يقارن بين شبكة عصبية وشجرة قرار لتصنيف خطر اكتئاب ما بعد الولادة من بيانات استبيانات صحية." }, s: "ann · decision trees · python" },
  { year: "2024", cat: { en: "Data Viz", ar: "تصوير بيانات" }, h: { en: "PCOS Women’s-Health Dashboards", ar: "لوحات بيانات لمتلازمة تكيّس المبايض" }, p: { en: "Static and interactive visualizations exploring Polycystic Ovary Syndrome data in R — turning a complex women’s-health dataset into a clear, explorable story.", ar: "تصوّرات ثابتة وتفاعلية لبيانات متلازمة تكيّس المبايض بلغة R — تحويل بيانات صحية معقّدة إلى قصة واضحة وقابلة للاستكشاف." }, s: "r · ggplot2 · interactive viz" },
  { year: "2024", cat: { en: "Machine Learning", ar: "تعلّم الآلة" }, h: { en: "Room Occupancy Estimation", ar: "تقدير إشغال الغرف" }, p: { en: "A supervised-learning pipeline estimating room occupancy from multi-sensor environmental data — feature engineering, model selection, and rigorous evaluation.", ar: "خط تعلّم خاضع للإشراف يقدّر إشغال الغرف من بيانات حسّاسات بيئية متعددة — هندسة خصائص واختيار نماذج وتقييم دقيق." }, s: "scikit-learn · classification" },
  { year: "2024", cat: { en: "Big Data", ar: "بيانات ضخمة" }, h: { en: "Big Data on Hadoop & Docker", ar: "بيانات ضخمة على Hadoop وDocker" }, p: { en: "Distributed data processing built on a containerised Hadoop cluster — hands-on with the infrastructure side of working at scale.", ar: "معالجة بيانات موزّعة على عنقود Hadoop داخل حاويات — تطبيق عملي للبنية التحتية للعمل على نطاق واسع." }, s: "hadoop · docker · big data" },
  { year: "2024", cat: { en: "BI", ar: "ذكاء أعمال" }, h: { en: "LinkedIn Job-Market Dashboard", ar: "لوحة سوق العمل من LinkedIn" }, p: { en: "A Power BI business-intelligence dashboard surfacing hiring trends and in-demand skills from a large LinkedIn job-postings dataset.", ar: "لوحة Power BI لذكاء الأعمال تُبرز اتجاهات التوظيف والمهارات المطلوبة من بيانات وظائف LinkedIn الضخمة." }, s: "power bi · dax · storytelling" },
  { year: "2024", cat: { en: "Bioinformatics", ar: "معلوماتية حيوية" }, h: { en: "Gene-Expression Analysis (DESeq)", ar: "تحليل التعبير الجيني (DESeq)" }, p: { en: "Differential gene-expression analysis on RNA-seq data using DESeq in R — connecting statistics to the biology underneath.", ar: "تحليل التعبير الجيني التفاضلي على بيانات RNA-seq باستخدام DESeq في R — ربط الإحصاء بالأحياء الكامنة." }, s: "r · deseq · statistics" },
  { year: "2024", cat: { en: "Security", ar: "أمن" }, h: { en: "Security Risk Analysis", ar: "تحليل المخاطر الأمنية" }, p: { en: "A structured security risk assessment for a case-study organisation — threat modelling, risk scoring, and prioritised mitigations.", ar: "تقييم منظَّم للمخاطر الأمنية لمؤسسة دراسة حالة — نمذجة تهديدات وتسجيل مخاطر وإجراءات تخفيف مرتّبة بالأولوية." }, s: "risk analysis · threat modelling" },
  { year: "2025–", cat: { en: "Fellowship", ar: "زمالة" }, h: { en: "9XAI Fellowship", ar: "زمالة 9XAI" }, p: { en: "Currently building real-world, applied AI as a 9XAI Fellow — taking models from notebook experiments to things people can actually use.", ar: "أبني حاليًا ذكاءً اصطناعيًا تطبيقيًا كزميلة في 9XAI — أنقل النماذج من تجارب المفكرات إلى منتجات يستخدمها الناس فعلًا." }, s: "applied ai · product" },
];

const dc = (n: string, c: string): LightboxItem => ({ src: `certs/datacamp/${n}`, cap: { en: c, ar: c } });
// `sort` = YYYYMM for strict newest→oldest ordering; `date` = year shown on the badge.
export const credentials: Credential[] = [
  { date: 2025, sort: 202506, cat: "impact", img: "certs/qrne.jpg", title: { en: "QRNE Entrepreneurship", ar: "ريادة الأعمال QRNE" }, issuer: { en: "Queen Rania Centre · Attendance · 6 May – 3 June 2025", ar: "مركز الملكة رانيا · حضور · ٦ مايو – ٣ يونيو ٢٠٢٥" } },
  { date: 2025, sort: 202505, cat: "award", img: "certs/excellence-2.jpg", title: { en: "HTU Excellence Award (II)", ar: "جائزة التميّز من الجامعة (٢)" }, issuer: { en: "Al Hussein Technical University · 2025", ar: "جامعة الحسين التقنية · ٢٠٢٥" } },
  { date: 2025, sort: 202504, cat: "award", img: "certs/ahli-fintech.jpg", title: { en: "Ahli Fintech Hackathon", ar: "هاكاثون الأهلي فينتك" }, issuer: { en: "Ahli Fintech · April 2025", ar: "الأهلي فينتك · أبريل ٢٠٢٥" } },
  { date: 2024, sort: 202410, cat: "data", img: "certs/web-scraping-python.jpg", title: { en: "Web Scraping with Python", ar: "تجميع بيانات الويب ببايثون" }, issuer: { en: "Great Learning Academy · Oct 2024", ar: "Great Learning · أكتوبر ٢٠٢٤" } },
  { date: 2024, sort: 202410, cat: "data", img: "certs/kbw-bootcamp.jpg", title: { en: "AI & Data Science in Transportation", ar: "الذكاء الاصطناعي وعلم البيانات في النقل" }, issuer: { en: "KBW Smart Solutions · 255 hrs · Mar–Oct 2024", ar: "KBW · ٢٥٥ ساعة · ٢٠٢٤" } },
  { date: 2024, sort: 202410, cat: "award", img: "certs/hakeem.jpg", title: { en: "Hakeem — Winner (The Nur Project)", ar: "حكيم — الفائزة (مشروع نور)" }, issuer: { en: "Electronic Health Solutions · Oct 2024", ar: "الحلول الصحية الإلكترونية · أكتوبر ٢٠٢٤" } },
  { date: 2024, sort: 202409, cat: "data", img: "certs/uipath-rpa-diploma.jpg", title: { en: "Robotic Process Automation with UiPath", ar: "أتمتة العمليات الآلية بـ UiPath" }, issuer: { en: "Kubicle · Diploma · Sep 2024", ar: "Kubicle · دبلوم · سبتمبر ٢٠٢٤" } },
  { date: 2024, sort: 202406, cat: "award", img: "certs/excellence-1.jpg", title: { en: "HTU Excellence Award (I)", ar: "جائزة التميّز من الجامعة (١)" }, issuer: { en: "Al Hussein Technical University · 2024", ar: "جامعة الحسين التقنية · ٢٠٢٤" } },
  { date: 2024, sort: 202403, cat: "data", badge: 14, cover: "certs/pwc/01-diploma.jpg", title: { en: "PwC Kubicle Diploma", ar: "دبلوم PwC Kubicle" }, issuer: { en: "PwC Academy ME · Digital Heroes · Mar 2024 · 14 certificates", ar: "أكاديمية PwC الشرق الأوسط · الأبطال الرقميون · ١٤ شهادة" }, set: [
    ...["01-diploma","02-data-literacy","03-data-databases","04-thinking-data","05-formulas","06-data-manipulation","07-text-time-dates","08-charts-in-depth","09-chart-selection","10-first-dashboard","11-powerbi-viz","12-ppt-fundamentals","13-presentation-design","14-presentation-visuals"].map((n)=>({ src:`certs/pwc/${n}.jpg`, cap:{en:"PwC Kubicle",ar:"PwC Kubicle"} })) ] },
  { date: 2024, sort: 202403, cat: "data", img: "certs/pwc-digital-heroes.jpg", title: { en: "PwC ME Digital Heroes", ar: "PwC الشرق الأوسط — الأبطال الرقميون" }, issuer: { en: "PwC Academy ME · Phoenix Space · Mar 2024", ar: "أكاديمية PwC الشرق الأوسط · مارس ٢٠٢٤" } },
  { date: 2024, sort: 202402, cat: "data", img: "certs/amideast-c2.jpg", title: { en: "English · C2 Proficiency", ar: "الإنجليزية · إتقان C2" }, issuer: { en: "AMIDEAST · Feb 2024 · 59.7 / 60 (C2)", ar: "AMIDEAST · فبراير ٢٠٢٤ · 59.7 / 60" } },
  { date: 2024, sort: 202401, cat: "impact", img: "certs/clubs-recognition.jpg", title: { en: "Club Leadership", ar: "قيادة الأندية" }, issuer: { en: "HTU · ACM & GDVC · 2024", ar: "الجامعة · ACM وGDVC · ٢٠٢٤" } },
  { date: 2024, sort: 202401, cat: "impact", img: "certs/volunteering.jpg", title: { en: "Volunteering Recognition", ar: "تكريم التطوّع" }, issuer: { en: "HTU · 2023–2024", ar: "الجامعة · ٢٠٢٣–٢٠٢٤" } },
  { date: 2024, sort: 202401, cat: "award", img: "certs/scholarship.jpg", title: { en: "Scholarship Award", ar: "منحة دراسية" }, issuer: { en: "HTU · 2023–2024", ar: "الجامعة · ٢٠٢٣–٢٠٢٤" } },
  { date: 2023, sort: 202310, cat: "data", badge: 9, cover: "certs/google-data-analytics.jpg", title: { en: "Google Data Analytics", ar: "تحليل البيانات من Google" }, issuer: { en: "Google · Coursera · Oct 2023 · 8 courses", ar: "Google · كورسيرا · أكتوبر ٢٠٢٣" }, set: [
    { src: "certs/google-data-analytics.jpg", cap: { en: "Professional Certificate", ar: "الشهادة المهنية" } },
    ...["01-foundations","02-ask-questions","03-prepare-data","04-process-data","05-analyze-data","06-share-data","07-r-programming","08-capstone"].map((n)=>({ src:`certs/google/${n}.jpg`, cap:{en:"Google Data Analytics",ar:"تحليل البيانات من Google"} })) ] },
  { date: 2023, sort: 202309, cat: "data", badge: 14, cover: "certs/datacamp/01-intro-python.jpg", title: { en: "DataCamp — 14 Courses", ar: "DataCamp — ١٤ دورة" }, issuer: { en: "Python, ML & AI · 2023", ar: "بايثون وتعلّم الآلة والذكاء الاصطناعي · ٢٠٢٣" }, set: [
    dc("01-intro-python.jpg","Introduction to Python"), dc("02-intermediate-python.jpg","Intermediate Python"), dc("03-ds-toolbox.jpg","Python Data Science Toolbox"), dc("04-joining-pandas.jpg","Joining Data with pandas"), dc("05-pandas.jpg","Data Manipulation with pandas"), dc("06-numpy.jpg","Introduction to NumPy"), dc("07-understanding-ds.jpg","Understanding Data Science"), dc("08-understanding-ml.jpg","Understanding Machine Learning"), dc("09-understanding-ai.jpg","Understanding Artificial Intelligence"), dc("10-ai-fundamentals.jpg","AI Fundamentals"), dc("11-ai-ethics.jpg","AI Ethics"), dc("12-generative-ai.jpg","Generative AI Concepts"), dc("13-llm-concepts.jpg","Large Language Models Concepts"), dc("14-intro-chatgpt.jpg","Introduction to ChatGPT") ] },
  { date: 2023, sort: 202307, cat: "data", img: "certs/datacamp-associate-ds.jpg", title: { en: "Associate Data Scientist", ar: "عالِمة بيانات مشارِكة" }, issuer: { en: "DataCamp · Jul 2023", ar: "DataCamp · يوليو ٢٠٢٣" } },
  { date: 2023, sort: 202301, cat: "award", img: "certs/math-participation.jpg", title: { en: "Mathematics Competition", ar: "مسابقة الرياضيات" }, issuer: { en: "HTU · 2023", ar: "الجامعة · ٢٠٢٣" } },
  { date: 2022, sort: 202211, cat: "data", badge: 3, cover: "certs/gdsc.jpg", title: { en: "Google Cloud · Big Data & ML", ar: "Google Cloud · البيانات الضخمة وتعلّم الآلة" }, issuer: { en: "GDSC HTU & Google Cloud · Nov 2022 · 3 certificates", ar: "أندية مطوّري Google · نوفمبر ٢٠٢٢ · ٣ شهادات" }, set: [
    { src:"certs/gdsc.jpg", cap:{en:"GDSC Study Jam — Big Data & ML Fundamentals",ar:"معسكر GDSC"} },
    { src:"certs/gcloud-bigdata-ml.jpg", cap:{en:"Google Cloud Big Data & ML Fundamentals",ar:"Google Cloud"} },
    { src:"certs/gcloud-how-google-ml.jpg", cap:{en:"How Google Does Machine Learning",ar:"Google Cloud"} } ] },
  { date: 2022, sort: 202210, cat: "data", badge: 5, cover: "certs/coursera/relational-db-sql.jpg", title: { en: "Coursera Guided Projects", ar: "مشاريع كورسيرا الموجَّهة" }, issuer: { en: "Coursera Project Network · Oct 2022 · 5 projects", ar: "شبكة مشاريع كورسيرا · أكتوبر ٢٠٢٢ · ٥ مشاريع" }, set: [
    { src:"certs/coursera/relational-db-sql.jpg", cap:{en:"Relational Database and SQL",ar:"قواعد البيانات وSQL"} },
    { src:"certs/coursera/power-bi.jpg", cap:{en:"Power BI",ar:"Power BI"} },
    { src:"certs/coursera/cisco-networks.jpg", cap:{en:"Networks and Cisco Devices",ar:"الشبكات وأجهزة Cisco"} },
    { src:"certs/coursera/figma.jpg", cap:{en:"Get Started with Figma",ar:"البدء مع Figma"} },
    { src:"certs/coursera/organic-marketing-facebook.jpg", cap:{en:"Organic Marketing: Facebook Groups",ar:"التسويق العضوي"} } ] },
  { date: 2022, sort: 202210, cat: "award", img: "certs/acm-cpc.jpg", title: { en: "ACM Programming Contest", ar: "مسابقة ACM للبرمجة" }, issuer: { en: "ACM · Competitive programming · 2022", ar: "برمجة تنافسية · ٢٠٢٢" } },
  { date: 2022, sort: 202210, cat: "award", img: "certs/acm-october.jpg", title: { en: "ACM October Contest", ar: "مسابقة ACM أكتوبر" }, issuer: { en: "ACM · October 2022", ar: "ACM · أكتوبر ٢٠٢٢" } },
  { date: 2022, sort: 202210, cat: "award", img: "certs/ieee.jpg", title: { en: "IEEEXtreme", ar: "IEEEXtreme" }, issuer: { en: "IEEE · 2022 · Participant", ar: "IEEE · ٢٠٢٢ · مشارِكة" } },
  { date: 2022, sort: 202210, cat: "impact", img: "certs/women-in-tech.jpg", title: { en: "Women in Tech Program", ar: "برنامج المرأة في التقنية" }, issuer: { en: "Zain Jordan · 2022–2023", ar: "زين الأردن · ٢٠٢٢–٢٠٢٣" } },
  { date: 2022, sort: 202206, cat: "data", img: "certs/aws.jpg", title: { en: "AWS — App Development", ar: "AWS — تطوير التطبيقات" }, issuer: { en: "Amazon Web Services · 2022", ar: "Amazon Web Services · ٢٠٢٢" } },
  { date: 2022, sort: 202205, cat: "award", img: "certs/math-marathon.jpg", title: { en: "Math Marathon Finalist", ar: "متأهلة ماراثون الرياضيات" }, issuer: { en: "HTU · Spring 2022", ar: "الجامعة · ربيع ٢٠٢٢" } },
  { date: 2022, sort: 202203, cat: "impact", img: "certs/acm-training.jpg", title: { en: "ACM Training Program", ar: "برنامج تدريب ACM" }, issuer: { en: "ACM · 2022", ar: "ACM · ٢٠٢٢" } },
  { date: 2022, sort: 202203, cat: "impact", img: "certs/wikigap.jpg", title: { en: "WikiGap Contributor", ar: "مساهِمة WikiGap" }, issuer: { en: "Wikipedia × Sweden MFA · 2022", ar: "ويكيبيديا × خارجية السويد · ٢٠٢٢" } },
  { date: 2022, sort: 202201, cat: "impact", img: "certs/ana-usharek.jpg", title: { en: "Ana Usharek", ar: "أنا أشارك" }, issuer: { en: "Civic participation · 2022", ar: "مشاركة مدنية · ٢٠٢٢" } },
  { date: 2021, sort: 202110, cat: "impact", badge: 14, cover: "certs/unwomen-iknowgender.jpg", title: { en: "UN Women · I Know Gender", ar: "هيئة الأمم للمرأة · أعرف النوع الاجتماعي" }, issuer: { en: "UN Women Training Centre · Oct 2021 · 16 modules", ar: "مركز تدريب هيئة الأمم للمرأة · أكتوبر ٢٠٢١ · ١٦ وحدة" }, set: [
    { src:"certs/unwomen/01-modules-1-3.jpg", cap:{en:"Modules 1–3",ar:"الوحدات ١–٣"} },
    ...["04","05","06","07","08","09","10","11","12","13","14","15","16"].map((n)=>({ src:`certs/unwomen/${n}.jpg`, cap:{en:`Module ${n}`,ar:`الوحدة ${n}`} })) ] },
  { date: 2020, sort: 202001, cat: "impact", badge: 4, cover: "certs/school/01.jpg", title: { en: "School Certificates", ar: "شهادات مدرسية" }, issuer: { en: "Pre-university · 4 certificates", ar: "ما قبل الجامعة · ٤ شهادات" }, set: [
    ...["01","02","03","04"].map((n)=>({ src:`certs/school/${n}.jpg`, cap:{en:"School certificate",ar:"شهادة مدرسية"} })) ] },
  { date: 2026, sort: 202606, cat: "award", doc: "pdf", href: "certs/TOEFL_Score_Report_3145188.pdf", title: { en: "TOEFL Score Report", ar: "نتيجة اختبار التوفل" }, issuer: { en: "ETS TOEFL iBT · 2026", ar: "ETS TOEFL iBT · ٢٠٢٦" } },
];

export const writings: Writing[] = [
  { date: 2023, sort: 202301, doc: "docx", href: "writings/feminism.docx", title: { en: "On Feminism", ar: "عن النسوية" }, blurb: { en: "A personal essay reflecting on feminism.", ar: "مقالة شخصية تتأمل في النسوية." }, body: feminismEssay },
  { date: 2021, sort: 202111, doc: "docx", href: "writings/jordan-paper.docx", title: { en: "On Jordan's Pandemic Response", ar: "عن استجابة الأردن لجائحة كورونا" }, blurb: { en: "A discursive essay on how effectively Jordan handled COVID-19 compared to the rest of the world.", ar: "مقالة نقاشية تقيّم مدى فعالية تعامل الأردن مع جائحة كورونا مقارنة بالعالم." }, body: jordanEssay },
];

export const TECH: string[] = ["Python","R","SQL","pandas","NumPy","scikit-learn","Power BI","Tableau","Hadoop","Docker","Java","C / C++","Jupyter","ggplot2","Git","Excel","LLM concepts","Neural Networks"];
